window.czData = {
  "zones": [
    "Blood Moor and Den of Evil",
    "Cold Plains and the Cave",
    "Stony Field and Tristram",
    "Dark Wood and the Underground Passage",
    "Black Marsh and the Hole",
    "Tamoe Highland and the Pit",
    "Burial Ground and Mausoleum",
    "Forgotten Tower",
    "Outer Cloister and Barracks",
    "Jail, Inner Cloister, and Cathedral",
    "Catacombs",
    "Cow Level",
    "Rocky Waste and the Stony Tomb",
    "Dry Hills and the Halls of the Dead",
    "Far Oasis and the Maggot Lair",
    "Lost City, Ancient Tunnels, and Claw Viper Temple",
    "Canyon of the Magi and Tal Rasha's Tomb",
    "Lut Gholein Sewers and the Palace Cellars",
    "Arcane Sanctuary",
    "Spider Forest, Arachnid Lair, and Spider Cavern",
    "Great Marsh and the Swampy Pit",
    "Flayer Jungle and the Flayer Dungeon",
    "Lower Kurast and the Kurast Sewers",
    "Kurast Bazaar, Ruined Temple, and Disused Fane",
    "Upper Kurast, the Forgotten Reliquary, and Forgotten Temple",
    "Travincal, the Ruined Fane, and Disused Reliquary",
    "Durance of Hate",
    "Outer Steppes and the Plains of Despair",
    "City of the Damned and the River of Flame",
    "Chaos Sanctuary",
    "Bloody Foothills and the Frigid Highlands",
    "Arreat Plateau, Crystalline Passage, and Frozen River",
    "Glacial Trail, Drifter Cavern, and Frozen Tundra",
    "Ancients' Way and the Icy Cellar",
    "Nihlathak's Temple",
    "Abaddon, the Pit of Acheron, and the Infernal Pit",
    "Worldstone Keep and Throne of Destruction"
  ],
  "zoneAct": [1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,4,4,4,5,5,5,5,5,5,5],
  "topZones": [35,21,28,19,14,17,20],
  "goodZones": [18,31,34,23,16,13,25],
  "redZones": [35],
  "zoneImmunities": {
    "0":["cold","fire"],
    "1":["cold","fire","lightning"],
    "2":["cold","fire","lightning","poison"],
    "3":["cold","fire","lightning","poison"],
    "4":["cold","fire","lightning","poison"],
    "5":["cold","fire","lightning","poison"],
    "6":["lightning"],
    "7":["fire","lightning","physical"],
    "8":["cold","fire","poison"],
    "9":["fire","lightning","physical","poison"],
    "10":["cold","fire","lightning"],
    "11":[],
    "12":["cold","fire","lightning","poison"],
    "13":["cold","fire","lightning","poison"],
    "14":["lightning","physical","poison"],
    "15":["cold","fire","lightning","magic","poison"],
    "16":["cold","fire","lightning","magic","physical","poison"],
    "17":["cold","fire","lightning","magic","poison"],
    "18":["cold","fire","physical"],
    "19":["cold","fire","lightning","poison"],
    "20":["cold","fire","lightning","poison"],
    "21":["cold","fire","lightning","physical","poison"],
    "22":["cold","fire","lightning","magic","poison"],
    "23":["cold","fire","magic","physical"],
    "24":["cold","fire","lightning","magic"],
    "25":["cold","fire","lightning"],
    "26":["cold","lightning","poison"],
    "27":["cold","fire","lightning","poison"],
    "28":["cold","fire","lightning","poison"],
    "29":["cold","fire","lightning"],
    "30":["cold","fire","lightning","poison"],
    "31":["cold","fire","lightning","physical","poison"],
    "32":["cold","fire","lightning","physical","poison"],
    "33":["cold","fire","lightning","physical","poison"],
    "34":["cold","fire","lightning","magic","physical","poison"],
    "35":["cold","fire","lightning","magic","physical","poison"],
    "36":["cold","fire","lightning","magic","physical","poison"]
  }
};
